	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DARKNESS_ENERGY             ; $07
	const DOUBLE_COLORLESS_ENERGY     ; $08
	const BULBASAUR                   ; $09
	const IVYSAUR                     ; $0a
	const VENUSAUR_LV64               ; $0b
	const VENUSAUR_LV67               ; $0c
	const CATERPIE                    ; $0d
	const METAPOD                     ; $0e
	const BUTTERFREE                  ; $0f
	const WEEDLE                      ; $10
	const KAKUNA                      ; $11
	const BEEDRILL                    ; $12
	const EKANS                       ; $13
	const ARBOK                       ; $14
	const NIDORANF                    ; $15
	const NIDORINA                    ; $16
	const NIDOQUEEN                   ; $17
	const NIDORANM                    ; $18
	const NIDORINO                    ; $19
	const NIDOKING                    ; $1a
	const ZUBAT                       ; $1b
	const GOLBAT                      ; $1c
	const CROBAT                      ; $1d
	const ODDISH                      ; $1e
	const GLOOM                       ; $1f
	const VILEPLUME                   ; $20
	const PARAS                       ; $21
	const PARASECT                    ; $22
	const VENONAT                     ; $23
	const VENOMOTH                    ; $24
	const BELLSPROUT                  ; $25
	const WEEPINBELL                  ; $26
	const VICTREEBEL                  ; $27
	const GRIMER                      ; $28
	const MUK                         ; $29
	const EXEGGCUTE                   ; $2a
	const EXEGGUTOR                   ; $2b
	const KOFFING                     ; $2c
	const WEEZING                     ; $2d
	const TANGELA                     ; $2e
	const SCYTHER                     ; $2f
	const PINSIR                      ; $30
	const LILEEP                      ; $31
	const CRADILY                     ; $32
	const CHARMANDER                  ; $33
	const CHARMELEON                  ; $34
	const CHARIZARD                   ; $35
	const VULPIX                      ; $36
	const NINETALES_LV32              ; $37
	const NINETALES_LV35              ; $38
	const GROWLITHE                   ; $39
	const ARCANINE_LV34               ; $3a
	const ARCANINE_LV45               ; $3b
	const PONYTA                      ; $3c
	const RAPIDASH                    ; $3d
	const MAGMAR_LV24                 ; $3e
	const MAGMAR_LV31                 ; $3f
	const FLAREON_LV22                ; $40
	const FLAREON_LV28                ; $41
	const MOLTRES_LV35                ; $42
	const MOLTRES_LV37                ; $43
	const SQUIRTLE                    ; $44
	const WARTORTLE                   ; $45
	const BLASTOISE                   ; $46
	const PSYDUCK                     ; $47
	const GOLDUCK                     ; $48
	const POLIWAG                     ; $49
	const POLIWHIRL                   ; $4a
	const POLIWRATH                   ; $4b
	const POLITOED                    ; $4c
	const TENTACOOL                   ; $4d
	const TENTACRUEL                  ; $4e
	const SEEL                        ; $4f
	const DEWGONG                     ; $50
	const SHELLDER                    ; $51
	const CLOYSTER                    ; $52
	const KRABBY                      ; $53
	const KINGLER                     ; $54
	const HORSEA                      ; $55
	const SEADRA                      ; $56
	const GOLDEEN                     ; $57
	const SEAKING                     ; $58
	const STARYU                      ; $59
	const STARMIE                     ; $5a
	const MAGIKARP                    ; $5b
	const GYARADOS                    ; $5c
	const GYARADOS_SHINY              ; $5d
	const LAPRAS                      ; $5e
	const VAPOREON_LV29               ; $5f
	const VAPOREON_LV42               ; $60
	const OMANYTE                     ; $61
	const OMASTAR                     ; $62
	const RELICANTH                   ; $63
	const ARTICUNO_LV35               ; $64
	const ARTICUNO_LV37               ; $65
	const PIKACHU_LV12                ; $66
	const PIKACHU_LV16                ; $67
	const FLYING_PIKACHU              ; $68
	const SURFING_PIKACHU             ; $69
	const RAICHU_LV35                 ; $6a
	const RAICHU_LV40                 ; $6b
	const RAICHU_LV45                 ; $6c
	const MAGNEMITE_LV15              ; $6d
	const MAGNETON_LV28               ; $6e
	const MAGNETON_LV35               ; $6f
	const VOLTORB                     ; $70
	const ELECTRODE_LV35              ; $71
	const ELECTRODE_LV42              ; $72
	const ELECTABUZZ_LV20             ; $73
	const ELECTABUZZ_LV35             ; $74
	const JOLTEON_LV24                ; $75
	const JOLTEON_LV29                ; $76
	const ZAPDOS_LV40                 ; $77
	const ZAPDOS_LV64                 ; $78
	const ZAPDOS_LV68                 ; $79
	const SANDSHREW                   ; $7a
	const SANDSLASH                   ; $7b
	const DIGLETT                     ; $7c
	const DUGTRIO                     ; $7d
	const MANKEY                      ; $7e
	const PRIMEAPE                    ; $7f
	const MACHOP                      ; $80
	const MACHOKE                     ; $81
	const MACHAMP                     ; $82
	const GEODUDE                     ; $83
	const GRAVELER                    ; $84
	const GOLEM                       ; $85
	const ONIX                        ; $86
	const CUBONE                      ; $87
	const MAROWAK_LV26                ; $88
	const MAROWAK_LV32                ; $89
	const HITMONLEE                   ; $8a
	const HITMONCHAN                  ; $8b
	const RHYHORN                     ; $8c
	const RHYDON                      ; $8d
	const KABUTO                      ; $8e
	const KABUTOPS                    ; $8f
	const ANORITH                     ; $90
	const ARMALDO                     ; $91
	const ABRA                        ; $92
	const KADABRA                     ; $93
	const ALAKAZAM                    ; $94
	const SLOWPOKE                    ; $95
	const SLOWBRO                     ; $96
	const GASTLY                      ; $97
	const HAUNTER_LV17                ; $98
	const HAUNTER_LV22                ; $99
	const GENGAR                      ; $9a
	const DROWZEE                     ; $9b
	const HYPNO                       ; $9c
	const MR_MIME                     ; $9d
	const JYNX                        ; $9e
	const MEWTWO_LV53                 ; $9f
	const MEWTWO_LV60                 ; $a0
	const MEW_LV8                     ; $a1
	const MEW_LV15                    ; $a2
	const PIDGEY                      ; $a3
	const PIDGEOTTO                   ; $a4
	const PIDGEOT_LV38                ; $a5
	const PIDGEOT_LV40                ; $a6
	const RATTATA                     ; $a7
	const RATICATE                    ; $a8
	const SPEAROW                     ; $a9
	const FEAROW                      ; $aa
	const CLEFAIRY                    ; $ab
	const CLEFABLE                    ; $ac
	const JIGGLYPUFF                  ; $ad
	const WIGGLYTUFF_LV28             ; $ae
	const WIGGLYTUFF_LV36             ; $af
	const MEOWTH_LV15                 ; $b0
	const PERSIAN                     ; $b1
	const FARFETCHD                   ; $b2
	const DODUO                       ; $b3
	const DODRIO                      ; $b4
	const LICKITUNG                   ; $b5
	const CHANSEY                     ; $b6
	const KANGASKHAN                  ; $b7
	const TAUROS                      ; $b8
	const DITTO                       ; $b9
	const EEVEE                       ; $ba
	const PORYGON                     ; $bb
	const AERODACTYL                  ; $bc
	const SNORLAX                     ; $bd
	const DRATINI                     ; $be
	const DRAGONAIR                   ; $bf
	const DRAGONITE_LV41              ; $c0
	const DRAGONITE_LV45              ; $c1
	const PROFESSOR_OAK               ; $c2
	const IMPOSTER_PROFESSOR_OAK      ; $c3
	const BILL                        ; $c4
	const MR_FUJI                     ; $c5
	const LASS                        ; $c6
	const IMAKUNI_CARD                ; $c7
	const POKEMON_TRADER              ; $c8
	const POKEMON_BREEDER             ; $c9
	const MYSTERIOUS_FOSSIL           ; $ca
	const ENERGY_RETRIEVAL            ; $cb
	const ENERGY_RECYCLER             ; $cc
	const ENERGY_SEARCH               ; $cd
	const ENERGY_REMOVAL              ; $ce
	const ENERGY_SWITCH               ; $cf
	const SWITCH                      ; $d0
	const POKEMON_FLUTE               ; $d1
	const POKE_BALL                   ; $d2
	const ULTRA_BALL                  ; $d3
	const SCOOP_UP                    ; $d4
	const COMPUTER_SEARCH             ; $d5
	const POKEDEX                     ; $d6
	const RECYCLE                     ; $d7
	const RARE_CANDY                  ; $d8
	const ITEM_FINDER                 ; $d9
	const GIOVANNI                    ; $da
	const DEVOLUTION_SPRAY            ; $db
	const POTION                      ; $dc
	const SUPER_POTION                ; $dd
	const FULL_HEAL                   ; $de
	const REVIVE                      ; $df
	const MAINTENANCE                 ; $e0
	const POKEMON_NURSE               ; $e1
	const PLUSPOWER                   ; $e2
	const DEFENDER                    ; $e3
	const SITRUS_BERRY                ; $e4
	const LUM_BERRY                   ; $e5
	const LEFTOVERS                   ; $e6
	const ROCKY_HELMET                ; $e7
	const MEMORY_CAPSULE              ; $e8
	const POKEMON_CENTER              ; $e9
	const VIRIDIAN_FOREST             ; $ea
	const PEWTER_GYM                  ; $eb
	const CERULEAN_GYM                ; $ec
	const VERMILION_GYM               ; $ed
	const CELADON_GYM                 ; $ee
	const FUCHSIA_GYM                 ; $ef
	const SAFFRON_GYM                 ; $f0
	const CINNABAR_GYM                ; $f1
	const VIRIDIAN_GYM                ; $f2
	const ROCKET_HEADQUARTERS         ; $f3
DEF NUM_CARDS EQU const_value - 1

DEF ENERGY_IDS_START  EQU GRASS_ENERGY
DEF POKEMON_IDS_START EQU BULBASAUR
DEF TRAINER_IDS_START EQU PROFESSOR_OAK
DEF STADIUM_IDS_START EQU POKEMON_CENTER
DEF TOOL_IDS_START    EQU PLUSPOWER
DEF TOOL_IDS_END      EQU STADIUM_IDS_START - 1

; special cards and alternative forms
	const_def 1
	const GRASSY_TERRAIN              ; $01
	const MYSTERIOUS_FOSSIL_PKMN      ; $02
DEF NUM_CARDS_ALT EQU const_value - 1

; card variants
DEF BLASTOISE_VARIANT EQU 1
DEF POLITOED_VARIANT EQU 0
DEF ZUBAT_VARIANT EQU 0
DEF MUK_VARIANT EQU 1

DEF POISON_BOOST_POKEMON_ID EQU 00
DEF BURN_BOOST_POKEMON_ID EQU 00
