	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DARKNESS_ENERGY             ; $07
	const DOUBLE_COLORLESS_ENERGY     ; $08
	const BULBASAUR                   ; $09
	const IVYSAUR                     ; $0a
	const VENUSAUR_LV64               ; $0b
	const VENUSAUR_LV67               ; $0c
	const CATERPIE                    ; $0d
	const METAPOD                     ; $0e
	const BUTTERFREE                  ; $0f
	const WEEDLE                      ; $10
	const KAKUNA                      ; $11
	const BEEDRILL                    ; $12
	const EKANS                       ; $13
	const ARBOK                       ; $14
	const NIDORANF                    ; $15
	const NIDORINA                    ; $16
	const NIDOQUEEN                   ; $17
	const NIDORANM                    ; $18
	const NIDORINO                    ; $19
	const NIDOKING                    ; $1a
	const ZUBAT                       ; $1b
	const GOLBAT                      ; $1c
	const ODDISH                      ; $1d
	const GLOOM                       ; $1e
	const VILEPLUME                   ; $1f
	const PARAS                       ; $20
	const PARASECT                    ; $21
	const VENONAT                     ; $22
	const VENOMOTH                    ; $23
	const BELLSPROUT                  ; $24
	const WEEPINBELL                  ; $25
	const VICTREEBEL                  ; $26
	const GRIMER                      ; $27
	const MUK                         ; $28
	const EXEGGCUTE                   ; $29
	const EXEGGUTOR                   ; $2a
	const KOFFING                     ; $2b
	const WEEZING                     ; $2c
	const TANGELA                     ; $2d
	const SCYTHER                     ; $2e
	const PINSIR                      ; $2f
	const CHARMANDER                  ; $30
	const CHARMELEON                  ; $31
	const CHARIZARD                   ; $32
	const VULPIX                      ; $33
	const NINETALES_LV32              ; $34
	const NINETALES_LV35              ; $35
	const GROWLITHE                   ; $36
	const ARCANINE_LV34               ; $37
	const ARCANINE_LV45               ; $38
	const PONYTA                      ; $39
	const RAPIDASH                    ; $3a
	const MAGMAR_LV24                 ; $3b
	const MAGMAR_LV31                 ; $3c
	const FLAREON_LV22                ; $3d
	const FLAREON_LV28                ; $3e
	const MOLTRES_LV35                ; $3f
	const MOLTRES_LV37                ; $40
	const SQUIRTLE                    ; $41
	const WARTORTLE                   ; $42
	const BLASTOISE                   ; $43
	const PSYDUCK                     ; $44
	const GOLDUCK                     ; $45
	const POLIWAG                     ; $46
	const POLIWHIRL                   ; $47
	const POLIWRATH                   ; $48
	const TENTACOOL                   ; $49
	const TENTACRUEL                  ; $4a
	const SEEL                        ; $4b
	const DEWGONG                     ; $4c
	const SHELLDER                    ; $4d
	const CLOYSTER                    ; $4e
	const KRABBY                      ; $4f
	const KINGLER                     ; $50
	const HORSEA                      ; $51
	const SEADRA                      ; $52
	const GOLDEEN                     ; $53
	const SEAKING                     ; $54
	const STARYU                      ; $55
	const STARMIE                     ; $56
	const MAGIKARP                    ; $57
	const GYARADOS                    ; $58
	const RED_GYARADOS                ; $59
	const LAPRAS                      ; $5a
	const VAPOREON_LV29               ; $5b
	const VAPOREON_LV42               ; $5c
	const OMANYTE                     ; $5d
	const OMASTAR                     ; $5e
	const ARTICUNO_LV35               ; $5f
	const ARTICUNO_LV37               ; $60
	const PIKACHU_LV12                ; $61
	const PIKACHU_LV16                ; $62
	const FLYING_PIKACHU              ; $63
	const SURFING_PIKACHU             ; $64
	const RAICHU_LV35                 ; $65
	const RAICHU_LV40                 ; $66
	const RAICHU_LV45                 ; $67
	const MAGNEMITE_LV15              ; $68
	const MAGNETON_LV28               ; $69
	const MAGNETON_LV35               ; $6a
	const VOLTORB                     ; $6b
	const ELECTRODE_LV35              ; $6c
	const ELECTRODE_LV42              ; $6d
	const ELECTABUZZ_LV20             ; $6e
	const ELECTABUZZ_LV35             ; $6f
	const JOLTEON_LV24                ; $70
	const JOLTEON_LV29                ; $71
	const ZAPDOS_LV40                 ; $72
	const ZAPDOS_LV64                 ; $73
	const ZAPDOS_LV68                 ; $74
	const SANDSHREW                   ; $75
	const SANDSLASH                   ; $76
	const DIGLETT                     ; $77
	const DUGTRIO                     ; $78
	const MANKEY                      ; $79
	const PRIMEAPE                    ; $7a
	const MACHOP                      ; $7b
	const MACHOKE                     ; $7c
	const MACHAMP                     ; $7d
	const GEODUDE                     ; $7e
	const GRAVELER                    ; $7f
	const GOLEM                       ; $80
	const ONIX                        ; $81
	const CUBONE                      ; $82
	const MAROWAK_LV26                ; $83
	const MAROWAK_LV32                ; $84
	const HITMONLEE                   ; $85
	const HITMONCHAN                  ; $86
	const RHYHORN                     ; $87
	const RHYDON                      ; $88
	const KABUTO                      ; $89
	const KABUTOPS                    ; $8a
	const ABRA                        ; $8b
	const KADABRA                     ; $8c
	const ALAKAZAM                    ; $8d
	const SLOWPOKE_LV9                ; $8e
	const SLOWBRO                     ; $8f
	const GASTLY                      ; $90
	const HAUNTER_LV17                ; $91
	const HAUNTER_LV22                ; $92
	const GENGAR                      ; $93
	const DROWZEE                     ; $94
	const HYPNO                       ; $95
	const MR_MIME                     ; $96
	const JYNX                        ; $97
	const MEWTWO_LV53                 ; $98
	const MEWTWO_LV60                 ; $99
	const MEW_LV8                     ; $9a
	const MEW_LV15                    ; $9b
	const PIDGEY                      ; $9c
	const PIDGEOTTO                   ; $9d
	const PIDGEOT_LV38                ; $9e
	const PIDGEOT_LV40                ; $9f
	const RATTATA                     ; $a0
	const RATICATE                    ; $a1
	const SPEAROW                     ; $a2
	const FEAROW                      ; $a3
	const CLEFAIRY                    ; $a4
	const CLEFABLE                    ; $a5
	const JIGGLYPUFF                  ; $a6
	const WIGGLYTUFF_LV28             ; $a7
	const WIGGLYTUFF_LV36             ; $a8
	const MEOWTH_LV15                 ; $a9
	const PERSIAN                     ; $aa
	const FARFETCHD                   ; $ab
	const DODUO                       ; $ac
	const DODRIO                      ; $ad
	const LICKITUNG                   ; $ae
	const CHANSEY                     ; $af
	const KANGASKHAN                  ; $b0
	const TAUROS                      ; $b1
	const DITTO                       ; $b2
	const EEVEE                       ; $b3
	const PORYGON                     ; $b4
	const AERODACTYL                  ; $b5
	const SNORLAX                     ; $b6
	const DRATINI                     ; $b7
	const DRAGONAIR                   ; $b8
	const DRAGONITE_LV41              ; $b9
	const DRAGONITE_LV45              ; $ba
	const PROFESSOR_OAK               ; $bb
	const IMPOSTER_PROFESSOR_OAK      ; $bc
	const BILL                        ; $bd
	const MR_FUJI                     ; $be
	const LASS                        ; $bf
	const IMAKUNI_CARD                ; $c0
	const POKEMON_TRADER              ; $c1
	const POKEMON_BREEDER             ; $c2
	const MYSTERIOUS_FOSSIL           ; $c3
	const ENERGY_RETRIEVAL            ; $c4
	const ENERGY_RECYCLER             ; $c5
	const ENERGY_SEARCH               ; $c6
	const ENERGY_REMOVAL              ; $c7
	const ENERGY_SWITCH               ; $c8
	const SWITCH                      ; $c9
	const POKEMON_CENTER              ; $ca
	const POKE_BALL                   ; $cb
	const ULTRA_BALL                  ; $cc
	const SCOOP_UP                    ; $cd
	const COMPUTER_SEARCH             ; $ce
	const POKEDEX                     ; $cf
	const PLUSPOWER                   ; $d0
	const DEFENDER                    ; $d1
	const ITEM_FINDER                 ; $d2
	const GIOVANNI                    ; $d3
	const DEVOLUTION_SPRAY            ; $d4
	const POTION                      ; $d5
	const SUPER_POTION                ; $d6
	const FULL_HEAL                   ; $d7
	const REVIVE                      ; $d8
	const MAINTENANCE                 ; $d9
	const POKEMON_FLUTE               ; $da
	const GAMBLER                     ; $db
	const RECYCLE                     ; $dc
	const RARE_CANDY                  ; $dd
	const POKEMON_NURSE               ; $de
DEF NUM_CARDS EQU const_value - 1

DEF ENERGY_IDS_START  EQU GRASS_ENERGY
DEF POKEMON_IDS_START EQU BULBASAUR
DEF TRAINER_IDS_START EQU PROFESSOR_OAK
