	const_def
	const TILESET_OVERWORLD_MAP               ; $00
	const TILESET_MASON_LABORATORY            ; $01
	const TILESET_ISHIHARA                    ; $02
	const TILESET_CLUB_ENTRANCE               ; $03
	const TILESET_CLUB_LOBBY                  ; $04
	const TILESET_FIGHTING_CLUB               ; $05
	const TILESET_ROCK_CLUB                   ; $06
	const TILESET_WATER_CLUB                  ; $07
	const TILESET_LIGHTNING_CLUB              ; $08
	const TILESET_GRASS_CLUB                  ; $09
	const TILESET_PSYCHIC_CLUB                ; $0a
	const TILESET_SCIENCE_CLUB                ; $0b
	const TILESET_FIRE_CLUB                   ; $0c
	const TILESET_CHALLENGE_HALL              ; $0d
	const TILESET_POKEMON_DOME_ENTRANCE       ; $0e
	const TILESET_POKEMON_DOME                ; $0f
	const TILESET_HALL_OF_HONOR               ; $10
	const TILESET_CARD_POP                    ; $11
	const TILESET_MEDAL                       ; $12
	const TILESET_GAMEBOY_LINK                ; $13
	const TILESET_GAMEBOY_PRINTER             ; $14
	const TILESET_COLOSSEUM                   ; $15
	const TILESET_EVOLUTION                   ; $16
	const TILESET_MYSTERY                     ; $17
	const TILESET_LABORATORY                  ; $18
	const TILESET_CHARIZARD_INTRO             ; $19
	const TILESET_SCYTHER_INTRO               ; $1a
	const TILESET_AERODACTYL_INTRO            ; $1b
	const TILESET_JAPANESE_TITLE_SCREEN       ; $1c
	const TILESET_SOLID_TILES_1               ; $1d
	const TILESET_JAPANESE_TITLE_SCREEN_2     ; $1e
	const TILESET_SOLID_TILES_2               ; $1f
	const TILESET_PLAYER                      ; $20
	const TILESET_RONALD                      ; $21
	const TILESET_TITLE_SCREEN                ; $22
	const TILESET_COPYRIGHT                   ; $23
	const TILESET_NINTENDO                    ; $24
	const TILESET_COMPANIES                   ; $25
	const TILESET_SAM                         ; $26
	const TILESET_IMAKUNI                     ; $27
	const TILESET_NIKKI                       ; $28
	const TILESET_RICK                        ; $29
	const TILESET_KEN                         ; $2a
	const TILESET_AMY                         ; $2b
	const TILESET_ISAAC                       ; $2c
	const TILESET_MITCH                       ; $2d
	const TILESET_GENE                        ; $2e
	const TILESET_MURRAY                      ; $2f
	const TILESET_COURTNEY                    ; $30
	const TILESET_STEVE                       ; $31
	const TILESET_JACK                        ; $32
	const TILESET_ROD                         ; $33
	const TILESET_JOSEPH                      ; $34
	const TILESET_DAVID                       ; $35
	const TILESET_ERIK                        ; $36
	const TILESET_JOHN                        ; $37
	const TILESET_ADAM                        ; $38
	const TILESET_JONATHAN                    ; $39
	const TILESET_JOSHUA                      ; $3a
	const TILESET_NICHOLAS                    ; $3b
	const TILESET_BRANDON                     ; $3c
	const TILESET_MATTHEW                     ; $3d
	const TILESET_RYAN                        ; $3e
	const TILESET_ANDREW                      ; $3f
	const TILESET_CHRIS                       ; $40
	const TILESET_MICHAEL                     ; $41
	const TILESET_DANIEL                      ; $42
	const TILESET_ROBERT                      ; $43
	const TILESET_BRITTANY                    ; $44
	const TILESET_KRISTIN                     ; $45
	const TILESET_HEATHER                     ; $46
	const TILESET_SARA                        ; $47
	const TILESET_AMANDA                      ; $48
	const TILESET_JENNIFER                    ; $49
	const TILESET_JESSICA                     ; $4a
	const TILESET_STEPHANIE                   ; $4b
	const TILESET_AARON                       ; $4c

DEF NUM_TILESETS EQU const_value
